#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend anto-muli
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 450103-web-01 52.207.79.6
        server 450103-web-02 34.234.193.197
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
